### ISSUE TITLE
Chiarimenti.

### ISSUE THREAD

**Issue by cocolino83** [zioCristia/esp-energy-monitor-v1#1]
Ciao ti avevo scritto su YouTube scrivendoti che volevo realizzare il tuo progetto. Oggi mi sono finalmente arrivati tutti i componenti. Io avrei intenzione di leggere due linee di cosa il piano terra e il secondo piano, ho visto sullo schema del PCB che hai creato che sui jeck hai messo nel primo una resistenza da 100 ohm e nell'altra una da 47 ohm sono un po' confuso. Un'altra domanda i condensatori da 10 uf ma da quanti volt? Ultima domanda il codice va bene quello che hai pubblicato ho andrebbe modificato? Grazie mille 😀
![IMG_20230117_100707](https://user-images.githubusercontent.com/88486650/212855770-8c4ce400-b7e6-4e5a-bd3b-172ebdb17c22.jpg)

**Comment by zioCristia** [comment]
Ciao quelle resistenze sono definite "burden resistors" e servono a trasformare il segnale in volt e poter essere letto così da Arduino o altro dispositivo. Il loro valore deve essere calcolato con una formula perché dipendono dal massimo valore di corrente che pensi di dover misurare e dal sensore che hai. Alcuni sensori CT non hanno bisogno di queste resistenze perché sono direttamente con l'uscita in volt, devi vedere quello che hai preso. In ogni modo nel video (https://youtu.be/UY-CO4Zc2r0) spiego meglio come calcolarle o se vuoi più dettagli puoi leggere questa guida: https://docs.openenergymonitor.org/electricity-monitoring/ct-sensors/interface-with-arduino.html

Io i condensatori li ho presi da 50v.

Il codice dovresti modificarlo se non utilizzi il circuito per misurare i valori dei pannelli fotovoltaici e soprattutto se non hai un server HomeAssistant a casa non va bene.

Se hai altre domande scrivi direttamente per email a ilgaragedelbicchio@gmail.com o nei commenti del video di sopra. Sarò più reattivo!
